import{a as b,S as w,i as c}from"./assets/vendor-5YrzWRhu.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",S="51378325-85b2545a081812b2976a73b54";async function P(o,r=1,n=15){const a={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:n};return(await b.get(v,{params:a})).data}const d=document.querySelector(".gallery"),u=document.querySelector(".loader"),f=document.querySelector(".load-more-btn"),q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function B(o){const r=o.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:i,comments:p,downloads:L})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${n}" alt="${e}" />
      </a>
      <div class="info">
        <p>👍 ${t}</p>
        <p>👁️ ${i}</p>
        <p>💬 ${p}</p>
        <p>⬇️ ${L}</p>
      </div>
    </li>`).join("");d.insertAdjacentHTML("beforeend",r),q.refresh()}function E(){d.innerHTML=""}function M(){u.classList.remove("is-hidden")}function $(){u.classList.add("is-hidden")}function O(){f.classList.remove("is-hidden")}function m(){f.classList.add("is-hidden")}const y=document.querySelector(".form"),x=y.elements["search-text"],A=document.querySelector(".load-more-btn");let g="",s=1;const l=15;y.addEventListener("submit",async o=>{o.preventDefault();const r=x.value.trim();if(!r){c.warning({title:"Warning",message:"Please enter a search term!"});return}g=r,s=1,E(),m(),await h()});A.addEventListener("click",async()=>{s+=1,await h()});async function h(){try{M();const o=await P(g,s,l);if(o.hits.length===0&&s===1){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}B(o.hits);const r=Math.ceil(o.totalHits/l);if(s<r?O():(m(),c.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),s>1){const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:n*2,behavior:"smooth"})}}catch{c.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{$()}}
//# sourceMappingURL=index.js.map
